---
- name: Task 1-2 playbook
  hosts: nodes
  tasks:
    - name: Add parametrs in /etc/default/grub
      lineinfile:
        path: /etc/default/grub
        line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'

    - name: Apply grub configuration changes
      command: 'grub2-mkconfig -o /etc/default/grub' 
...
